#!/bin/sh

set -x

if git rev-parse --verify HEAD >/dev/null 2>&1
   :
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
# Redirect output to stderr.
exec 1>&2

IS_ERROR=0

# コミットされるファイルのうち、.phpで終わるもの
for FILE in `git diff --name-only --cached --diff-filter=ACMRTUXB | grep -vE "vendor/|vendor_custom/" | grep -E "php$|ctp$" `; do
    # phpシンタックスのチェック
    php -l $FILE || exit 1
    (vendor/bin/php-cs-fixer fix $FILE && git add $FILE)
    vendor/bin/phpmd $FILE text unusedcode || exit 1

done

# コミットされるファイルのうち、.jsで終わるもの
for FILE in `git diff --name-only --cached --diff-filter=ACMRTUXB | grep -vE "vendor/|vendor_custom/" | grep -E "js$" `; do
    npx prettier --config .prettierrc.js --write $FILE
    npx eslint -c .eslintrc.js $FILE || IS_ERROR=1
    git add $FILE
done

docker-compose run --rm web composer test || exit 1

exit $IS_ERROR
